{% set name = "diffprivlib" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8af1efa181dbdb309979936a4468fdd6a8a9f6489f63e1133a2f868e7e48896

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - joblib >=0.13.2
    - numpy >=1.15.0
    - python
    - scikit-learn >=0.20.3
    - scipy >=1.2.1

test:
  imports:
    - diffprivlib
    - diffprivlib.mechanisms
    - diffprivlib.mechanisms.transforms
    - diffprivlib.models
    - diffprivlib.tools

about:
  home: https://github.com/IBM/differential-privacy-library
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: IBM Differential Privacy Library
  doc_url: https://pypi.org/project/diffprivlib/
  dev_url: https://github.com/IBM/differential-privacy-library

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
