{% set name = "diffprivlib" %}
{% set version = "0.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/diffprivlib-{{ version }}.tar.gz
  sha256: f733e1d8b9665d32b265053dddc40eab072f784f8015e05ba11d30274351f2e9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - joblib >=0.16.0
    - numpy >=1.19.0
    - python >=3.7
    - scikit-learn >=0.23.0
    - scipy >=1.5.0
    - setuptools >=49.0.0

test:
  imports:
    - diffprivlib
    - diffprivlib.mechanisms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IBM/differential-privacy-library
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: IBM Differential Privacy Library
  doc_url: https://pypi.org/project/diffprivlib/
  dev_url: https://github.com/IBM/differential-privacy-library

extra:
  recipe-maintainers:
    - mxr-conda
